export const autocompleteData = [
  { text: "Apple" },
  { text: "Banana" },
  { text: "Cherry" },
  { text: "Date" },
  { text: "Elderberry" },
  { text: "Fig" },
  { text: "Grape" },
  { text: "Honeydew" },
  { text: "Kiwi" },
  { text: "Lemon" },
  { text: "Mango" },
  { text: "Nectarine" },
  { text: "Orange" },
  { text: "Papaya" },
  { text: "Quince" },
  { text: "Raspberry" },
  { text: "Strawberry" },
  { text: "Tangerine" },
  { text: "Ugli fruit" },
  { text: "Watermelon" },
];
